# Generated by Django 3.1.5 on 2021-01-31 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoActializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'PeriodosDeActualizacion',
            },
        ),
        migrations.CreateModel(
            name='FormularioActualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('fields', models.JSONField()),
                ('secciones', models.JSONField()),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Censos.periodoactializacion')),
            ],
            options={
                'db_table': 'FormulariosActualizacion',
            },
        ),
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('estado_censo', models.PositiveSmallIntegerField(choices=[(0, 'Censo Incompleto'), (1, 'Censo Completo')], default=0)),
                ('tipo_identificacion', models.PositiveSmallIntegerField(choices=[(0, 'Cedula'), (1, 'Ruc'), (2, 'Pasaporte')], default=0)),
                ('identificacion', models.CharField(max_length=30, unique=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fields', models.JSONField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Censos.periodoactializacion')),
            ],
            options={
                'db_table': 'Censos',
                'unique_together': {('periodo', 'identificacion')},
            },
        ),
    ]
