# Generated by Django 3.1.5 on 2021-01-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Censos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoactializacion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto')], default=1),
        ),
    ]
